#!/opt/bin/bash
# Apply network configuration for FreshTomato router
# This script runs ON the router via setup-server

set -euo pipefail

echo "Applying network configuration..."

# Configure persistent network settings via NVRAM
echo "- Configuring default gateway and DNS settings in NVRAM"

# Set WAN gateway (this should point to your ISP modem/main router)
nvram set wan_gateway="192.168.1.1"

# Set DNS servers for WAN
nvram set wan_dns="1.1.1.1 8.8.8.8"

# Ensure router uses static DNS (not DHCP from ISP)
nvram set wan_dns_auto=0

# Set LAN IP configuration
nvram set lan_ipaddr="192.168.1.2"
nvram set lan_netmask="255.255.255.0"
nvram set lan_gateway="192.168.1.1"

# Configure as LAN router (not WAN router)
nvram set wan_proto="disabled"

# Commit NVRAM changes for persistence
nvram commit

# Apply immediate network configuration (for current session)
echo "- Applying immediate network configuration"

# Add default route if not already present
if ! ip route show | grep -q "default via 192.168.1.1"; then
  route add default gw 192.168.1.1 2> /dev/null || true
fi

# Update resolv.conf for immediate DNS resolution
echo "- Updating DNS configuration"
cat > /tmp/resolv.conf << 'EOF'
# DNS servers for router internet access
# Generated by laingville dwaca router configuration
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

# Copy to system location (will be reset on reboot, but NVRAM settings will restore it)
cp /tmp/resolv.conf /etc/resolv.conf 2> /dev/null || true

# Test connectivity
echo "- Testing network connectivity"

# Test gateway reachability
if ping -c 1 -W 3 192.168.1.1 > /dev/null 2>&1; then
  echo "  ✓ Gateway 192.168.1.1 is reachable"
else
  echo "  ⚠ Warning: Gateway 192.168.1.1 is not reachable"
fi

# Test internet connectivity
if ping -c 1 -W 5 8.8.8.8 > /dev/null 2>&1; then
  echo "  ✓ Internet connectivity via IP is working"
else
  echo "  ⚠ Warning: Internet connectivity via IP failed"
fi

# Test DNS resolution
if nslookup google.com > /dev/null 2>&1; then
  echo "  ✓ DNS resolution is working"
else
  echo "  ⚠ Warning: DNS resolution failed"
fi

echo "Network configuration applied successfully"
echo ""
echo "Persistent settings configured in NVRAM:"
echo "  - WAN Gateway: 192.168.1.1"
echo "  - DNS Servers: 1.1.1.1, 8.8.8.8"
echo "  - LAN IP: 192.168.1.2/24"
echo ""
echo "Settings will persist across reboots via NVRAM configuration"
echo "Current routing table:"
ip route show
