# .github/workflows/container-lifecycle.yml
name: Container Lifecycle

on:
  # Run on PRs for validation
  pull_request:
    branches: [main]
    paths:
      - 'infra/flake.nix'
      - 'infra/flake.lock'
      - 'infra/overlays/**'
      - 'infra/tests/**'
      - '.github/workflows/container-lifecycle.yml'

  # Run on main for build+publish
  push:
    branches: [main]
    paths:
      - 'infra/flake.nix'
      - 'infra/flake.lock'
      - 'infra/overlays/**'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-test:
    name: ${{ github.event_name == 'pull_request' && 'Test' || 'Build' }} ${{ matrix.image }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # For push events
      pull-requests: write  # For PR comments

    strategy:
      fail-fast: false
      matrix:
        image:
          - laingville-devcontainer
          - example-python-devcontainer
          - example-python-runtime
          - example-node-devcontainer
          - example-node-runtime

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build ${{ matrix.image }} with Nix
        run: |
          echo "Building ${{ matrix.image }}..."
          nix build ./infra#${{ matrix.image }} --out-link result

      - name: Load image into Docker
        id: load
        run: |
          # Load the Nix-built image into Docker
          docker load < result

          # Get the image name from the loaded tarball
          IMAGE_NAME=$(docker images --format '{{.Repository}}:{{.Tag}}' | head -1)
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "Loaded image: $IMAGE_NAME"

      - name: Run environment validation tests
        run: |
          IMAGE="${{ steps.load.outputs.image_name }}"

          # Determine test type based on image name
          case "${{ matrix.image }}" in
            *node*)
              echo "Running Node.js environment tests..."
              docker run --rm \
                -v "${{ github.workspace }}/infra/tests:/tests:ro" \
                "$IMAGE" \
                bash /tests/test-node-environment.sh
              ;;
            *python*)
              echo "Running Python environment tests..."
              docker run --rm \
                -v "${{ github.workspace }}/infra/tests:/tests:ro" \
                "$IMAGE" \
                bash /tests/test-python-environment.sh 2>/dev/null \
                || echo "::warning::Python tests not implemented yet"
              ;;
            *)
              echo "Running basic container validation..."
              docker run --rm "$IMAGE" bash -c 'echo "Container starts successfully"'
              ;;
          esac

      # Publishing steps - only run on push to main
      - name: Generate image tags
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: tags
        run: |
          DATE=$(date +%Y-%m-%d)
          SHA=$(git rev-parse --short HEAD)
          echo "date=${DATE}" >> $GITHUB_OUTPUT
          echo "sha=${SHA}" >> $GITHUB_OUTPUT

      - name: Log in to Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          IMAGE="${{ steps.load.outputs.image_name }}"

          # Tag with date, SHA, and latest
          docker tag "$IMAGE" "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:${{ steps.tags.outputs.date }}"
          docker tag "$IMAGE" "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:${{ steps.tags.outputs.date }}-${{ steps.tags.outputs.sha }}"
          docker tag "$IMAGE" "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:latest"

          # Push all tags
          docker push "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:${{ steps.tags.outputs.date }}"
          docker push "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:${{ steps.tags.outputs.date }}-${{ steps.tags.outputs.sha }}"
          docker push "${{ env.REGISTRY }}/mrdavidlaing/laingville/${{ matrix.image }}:latest"

      - name: Test result summary
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ ${{ matrix.image }} tests passed"
          else
            echo "❌ ${{ matrix.image }} tests failed"
            exit 1
          fi

  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: always()

    steps:
      - name: Check results
        run: |
          if [ "${{ needs.build-and-test.result }}" = "success" ]; then
            echo "✅ All container tests passed"
            if [ "${{ github.event_name }}" = "push" ]; then
              echo "Images have been published to the registry."
            else
              echo "Container changes are validated and ready for merge."
            fi
          else
            echo "❌ Some container tests failed"
            echo ""
            echo "Please review the test results above and fix any issues."
            exit 1
          fi

      - name: Add summary to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{ needs.build-and-test.result }}';
            const emoji = status === 'success' ? '✅' : '❌';
            const message = status === 'success'
              ? 'All container environment tests passed! Changes are validated and safe to merge.'
              : 'Some container environment tests failed. Please review the logs and fix any issues.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## ${emoji} Container Environment Tests\n\n${message}\n\nSee workflow run for details: ${context.payload.repository.html_url}/actions/runs/${context.runId}`
            });
